# Base Image (Linux: ubuntu, Python: 3.8.8)
FROM continuumio/anaconda3:2021.05

# Install optuna
# RUN conda install -y optuna=2.8.0 -c conda-forge

# Install jupyter
# RUN conda install jupyter

# Install GSAS-II by using conda
# RUN conda install -y gsas2pkg -c briantoby
